CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0
);

INSERT INTO products (name, description, price, stock) VALUES
    ('Wireless Mouse', 'Ergonomic wireless mouse with USB receiver.', 19.99, 42),
    ('Mechanical Keyboard', 'Compact 65% mechanical keyboard, hot-swappable switches.', 74.50, 15),
    ('USB-C Hub', '7-in-1 USB-C hub with HDMI, SD card, and 100W passthrough.', 29.99, 60),
    ('Laptop Stand', 'Adjustable aluminum laptop stand, foldable.', 34.00, 25),
    ('27" 4K Monitor', 'Ultra HD IPS display with USB-C connectivity.', 329.99, 12),
    ('Noise-Cancelling Headphones', 'Over-ear wireless headphones with active noise cancellation.', 149.99, 30),
    ('Webcam 1080p', 'Full HD webcam with built-in privacy shutter.', 45.00, 50),
    ('Portable SSD 1TB', 'Compact external solid-state drive, USB 3.2.', 89.99, 40),
    ('Desk Lamp with Wireless Charger', 'LED desk lamp with built-in Qi charging pad.', 39.99, 22),
    ('Ergonomic Office Chair', 'Adjustable mesh-back chair with lumbar support.', 189.00, 8),
    ('Bluetooth Speaker', 'Compact portable speaker with 12-hour battery life.', 54.99, 35),
    ('Mechanical Pencil Set', 'Set of 3 precision mechanical pencils for the desk.', 12.50, 100),
    ('Standing Desk Converter', 'Height-adjustable desktop riser for sit-stand work.', 129.00, 10),
    ('Wireless Charging Pad', 'Fast-charge Qi pad compatible with most phones.', 24.99, 55),
    ('USB Microphone', 'Plug-and-play condenser mic for streaming and calls.', 69.00, 18),
    ('Laptop Sleeve 15"', 'Padded neoprene sleeve with front pocket.', 17.99, 70),
    ('Cable Management Kit', 'Set of clips and sleeves to tidy up desk cables.', 9.99, 120),
    ('Ring Light 10"', 'Adjustable LED ring light with phone clip and tripod.', 32.50, 28),
    ('Graphics Tablet', 'Digital drawing tablet with pressure-sensitive pen.', 79.99, 14),
    ('Smart Power Strip', 'Wi-Fi enabled power strip with individually controlled outlets.', 44.00, 33),
    ('Adjustable Monitor Arm', 'Single-arm mount with full tilt and swivel range.', 59.99, 20),
    ('Mini Fridge (Desk-Size)', 'Compact 6-liter fridge for drinks and snacks.', 65.00, 9),
    ('Blue Light Glasses', 'Anti-glare computer glasses, unisex frame.', 22.00, 80),
    ('Wireless Earbuds', 'True wireless earbuds with charging case.', 59.99, 45),
    ('Desk Mat XL', 'Extended waterproof desk mat, 90x40cm.', 19.50, 65),
    ('Label Maker', 'Portable Bluetooth label printer for home and office.', 38.00, 16),
    ('Surge Protector', '8-outlet surge protector with USB charging ports.', 27.99, 50),
    ('Whiteboard 24x36', 'Magnetic dry-erase whiteboard with aluminum frame.', 48.00, 12),
    ('Document Scanner', 'Portable duplex scanner with Wi-Fi transfer.', 149.00, 7),
    ('Ergonomic Keyboard Tray', 'Under-desk sliding tray with wrist support.', 42.00, 19)
ON CONFLICT DO NOTHING;
