apiVersion: v1
kind: Service
metadata:
  name: cloudcart-service
  namespace: cloudcart
spec:
  type: NodePort
  selector:
    app: cloudcart
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
