pipeline {
    agent any

    parameters {
        string(name: 'DEPLOY_HOST', defaultValue: '54.246.41.33', description: 'Public IP of the target EC2 instance')
    }

    environment {
        IMAGE_NAME = "cloudcart-app"
        DEPLOY_USER = "ubuntu"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Samerhajj/cloudcart-platform.git'
            }
        }

        stage('Build') {
            steps {
                sh 'docker build --memory=512m -t ${IMAGE_NAME}:latest .'
            }
        }

        stage('Test') {
            steps {
                sh '''
                    docker run -d \
                    --memory=256m \
                    --name test-container \
                    -p 5050:5000 \
                    -e FLASK_SECRET_KEY=test-key \
                    ${IMAGE_NAME}:latest

                    for i in {1..10}; do
                        if curl -f http://localhost:5050/; then
                            echo "Application is ready"
                            break
                        fi

                        echo "Waiting for Application..."
                        sleep 3
                    done

                    docker logs test-container

                    docker stop test-container
                    docker rm test-container
                '''
            }
        }

        stage('Deploy') {
            steps {
                sshagent(credentials: ['ec2-ssh-key']) {
                    sh '''
                        echo "DEPLOY_USER=$DEPLOY_USER"
                        echo "DEPLOY_HOST=$DEPLOY_HOST"

                        ssh -o StrictHostKeyChecking=no ${DEPLOY_USER}@${DEPLOY_HOST} '
                            cd /home/ubuntu/cloudcart-platform &&
                            git pull origin main &&
                            docker compose -f docker/docker-compose.yml up -d --build
                        '
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully — CloudCart deployed.'
        }

        failure {
            echo 'Pipeline failed — check logs above.'
        }
    }
}
