pipeline {
    agent any


    environment {
        IMAGE_NAME = "whereshadow/cloudcart-app"
        DEPLOY_USER = "ubuntu"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Samerhajj/cloudcart-platform.git'
            }
        }

        stage('Build') {
            steps {
                sh 'docker build --memory=512m -t ${IMAGE_NAME}:latest .'
            }
        }

        stage('Test') {
            steps {
                sh '''
                    docker run -d --memory=256m --name test-container -p 5050:5000 -e FLASK_SECRET_KEY=test-key ${IMAGE_NAME}:latest

                    SUCCESS=0
                    for i in $(seq 1 10); do
                        if curl -f http://localhost:5050/; then
                            SUCCESS=1
                            break
                        fi
                        echo "Waiting for application..."
                        sleep 3
                    done

                    if [ "$SUCCESS" -ne 1 ]; then
                        docker logs test-container
                        docker stop test-container
                        docker rm test-container
                        exit 1
                    fi

                    docker stop test-container
                    docker rm test-container
                '''
            }
        }

        stage('Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push ${IMAGE_NAME}:latest
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                   export KUBECONFIG=/home/jenkins/.kube/config
                    cd /opt/cloudcart-platform
                    git pull origin main
                    helm upgrade cloudcart-release kubernetes/cloudcart-chart -n cloudcart
                    kubectl rollout status deployment/cloudcart-app -n cloudcart 
                '''
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully — CloudCart deployed to Kubernetes.'
        }
        failure {
            echo 'Pipeline failed — check logs above.'
        }
    }
}